image: docker:latest

services:
    - docker:dind

stages:
    - build

before_script:
    # Login to Google Container Registry
    - base64 -d $GCP_SA_KEY | docker login -u _json_key --password-stdin https://gcr.io

build:
    stage: build
    script:
        # Build and tag image for both GCR registry
        - docker build -t gcr.io/k8s-tutorial-294821/k8s-tutorial:latest .
        # Push image to GCR
        - docker push gcr.io/k8s-tutorial-294821/k8s-tutorial:latest